const QUERY_KEY = {
  USER: {
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    GET_USER_QUOTA: 'GET_USER_QUOTA',
  },
  CONTACT: {
    SEND_CONTACT: 'SEND_CONTACT',
    GET_CONTACTS: 'GET_CONTACTS',
    GET_MY_CONTACTS: 'GET_MY_CONTACTS',
  },
  REVIEW: {
    GET_REVIEW_STATS: 'GET_REVIEW_STATS',
    GET_REVIEWS: 'GET_REVIEWS',
    SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  },
  EXAM: {
    LIST_EXAMS: 'LIST_EXAMS',
    START_EXAM: 'START_EXAM',
    ATTEMPT_DETAIL: 'ATTEMPT_DETAIL',
    SAVE_ANSWER: 'SAVE_ANSWER',
    SUBMIT_EXAM: 'SUBMIT_EXAM',
    ATTEMPT_RESULT: 'ATTEMPT_RESULT',
    LEADERBOARD: 'LEADERBOARD',
  },
  FLASHCARD: {
    LIST_SETS: 'LIST_FLASHCARD_SETS',
    GET_SET: 'GET_FLASHCARD_SET',
  },
  CHAT: {
    LIST_CONVERSATIONS: 'LIST_CHAT_CONVERSATIONS',
    LIST_MESSAGES: 'LIST_CHAT_MESSAGES',
  },
  SUBJECT: {
    LIST_SUBJECTS: 'LIST_SUBJECTS',
  },
  Test_CATEGORY: {
    LIST_TEST_CATEGORIES: 'LIST_TEST_CATEGORIES',
  },
  NOTIFICATION: {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    GET_UNREAD_COUNT: 'GET_UNREAD_COUNT',
  },
  PACKAGE: {
    LIST_PACKAGES: 'LIST_PACKAGES',
  },
  PAYMENT: {
    LIST_PAYMENTS: 'LIST_PAYMENTS',
    GET_PAYMENT_STATUS: 'GET_PAYMENT_STATUS',
  },
  ARTICLE: {
    LIST_ARTICLES: 'LIST_ARTICLES',
    GET_ARTICLE_BY_ID: 'GET_ARTICLE_BY_ID',
    GET_ARTICLE_BY_SLUG: 'GET_ARTICLE_BY_SLUG',
    FEATURED_ARTICLES: 'FEATURED_ARTICLES',
    LATEST_BY_CATEGORIES: 'LATEST_BY_CATEGORIES',
    MOST_VIEWED_BY_CATEGORIES: 'MOST_VIEWED_BY_CATEGORIES',
    RELATED_ARTICLES: 'RELATED_ARTICLES',
  },
  CATEGORY: {
    LIST_CATEGORIES: 'LIST_CATEGORIES',
    GET_CATEGORY_BY_ID: 'GET_CATEGORY_BY_ID',
    GET_CATEGORY_BY_SLUG: 'GET_CATEGORY_BY_SLUG',
  },
  TAG: {
    LIST_TAGS: 'LIST_TAGS',
    GET_TAG_BY_ID: 'GET_TAG_BY_ID',
    GET_TAG_BY_SLUG: 'GET_TAG_BY_SLUG',
  },
  SONG: {
    LIST: 'LIST_SONGS',
    DETAIL: 'SONG_DETAIL',
    SCORES: 'SONG_SCORES',
    SCORE_STATUS: 'SONG_SCORE_STATUS',
  },
};

export default QUERY_KEY;
