const QUERY_KEY = {
  USER: {
    GET_USER_BY_ID: 'GET_USER_BY_ID',
  },
  CONTACT: {
    SEND_CONTACT: 'SEND_CONTACT',
    GET_CONTACTS: 'GET_CONTACTS',
    GET_MY_CONTACTS: 'GET_MY_CONTACTS',
  },
  REVIEW: {
    GET_REVIEW_STATS: 'GET_REVIEW_STATS',
    GET_REVIEWS: 'GET_REVIEWS',
    SUBMIT_REVIEW: 'SUBMIT_REVIEW',
  },
  EXAM: {
    LIST_EXAMS: 'LIST_EXAMS',
    START_EXAM: 'START_EXAM',
    ATTEMPT_DETAIL: 'ATTEMPT_DETAIL',
    SAVE_ANSWER: 'SAVE_ANSWER',
    SUBMIT_EXAM: 'SUBMIT_EXAM',
    LEADERBOARD: 'LEADERBOARD',
  },
  FLASHCARD: {
    LIST_SETS: 'LIST_FLASHCARD_SETS',
    GET_SET: 'GET_FLASHCARD_SET',
  },
  SUBJECT: {
    LIST_SUBJECTS: 'LIST_SUBJECTS',
  },
  Test_CATEGORY: {
    LIST_TEST_CATEGORIES: 'LIST_TEST_CATEGORIES',
  },
  NOTIFICATION: {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    GET_UNREAD_COUNT: 'GET_UNREAD_COUNT',
  },
  PACKAGE: {
    LIST_PACKAGES: 'LIST_PACKAGES',
  },
};

export default QUERY_KEY;
